export class StyleConstants {
  /**
   * 组件宽度百分比: 100%.
   */
  static readonly FULL_WIDTH: string = '100%';
  /**
   * 组件高度百分比: 100%.
   */
  static readonly FULL_HEIGHT: string = '100%';
  /**
   * space 6
   */
  static readonly SPACE_6 = '6vp'
  /**
   * space 12
   */
  static readonly SPACE_12 = '12vp'
  /**
   * feature id
   */
  static readonly FEATURE_ID_DEVICE_INFO = 'feature_id_device_info'
  static readonly FEATURE_ID_NETWORK_INFO = 'feature_id_network_info'
  static readonly FEATURE_ID_DISPLAY = 'feature_id_display'
  static readonly FEATURE_ID_BATTERY_INFO = 'feature_id_battery_info'
  static readonly FEATURE_ID_APP_LIST = 'feature_id_app_list'
  static readonly FEATURE_ID_WEB_VIEW = 'feature_id_web_view'
}